language: python
python:
  - "2.7"
  - "3.5"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
cache: pip
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install cython
  - pip install git+https://github.com/mobiusklein/brainpy.git
  - pip install numpy
  - pip install scipy
  - pip install git+https://github.com/mobiusklein/ms_peak_picker.git
  - pip install -e .
  # - pip install -r requirements.txt
# command to run tests
script: nosetests
